VPMS/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.ObjectModel;
using VPMS.Lib.Data;
using VPMS.Lib.Data.Models;
using VPMSWeb.Lib.Settings;

namespace VPMSWeb.Controllers
{
    [Authorize]
    public class DoctorController : Controller
    {
        private readonly VPMS.Lib.Data.DBContext.ServicesDBContext _servicesDBContext = new VPMS.Lib.Data.DBContext.ServicesDBContext();
        public String sMasterDataGroupName = "Gender";

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Get Doctor Listing
        /// </summary>
        /// <param name="sKeyword"></param>
        /// <param name="pageSize"></param>
        /// <param name="pageIndex"></param>
        /// <returns></returns>
        public IActionResult GetDoctorViewList(String sKeyword, int organizationID, int branchID, int pageSize, int pageIndex)
        {
            int iTotalRecords;
            int isSuperadmin = 0;
            var organizationObj = OrganizationRepository.GetOrganizationByID(organizationID);
            if (organizationObj != null)
            {
                if (organizationObj.Level == 0 || organizationObj.Level == 1)
                {
                    isSuperadmin = 1;
                }
            }

            var sResult = DoctorRepository.GetDoctorViewList(ConfigSettings.GetConfigurationSettings(), isSuperadmin, sKeyword, organizationID, branchID, pageSize, pageIndex, out iTotalRecords);
            if (sResult != null)
            {
                return Json(new { data = sResult, totalRecord = iTotalRecords });
            }

            return null;
        }

        /// <summary>
        /// Add Doctor
        /// </summary>
        /// <param name="sDoctorModel"></param>
        /// <returns></returns>
        public IActionResult AddDoctor(NewDoctorControllerModel sDoctorModel)
        {
            VPMSWeb.Models.ResponseStatusObject sResp = new VPMSWeb.Models.ResponseStatusObject();
            DateTime sNow = DateTime.Now;

            DoctorModel sNewDoctor = new DoctorModel();
            sNewDoctor.Name = sDoctorModel.doctorName;
            sNewDoctor.Gender = sDoctorModel.doctorGender;
            sNewDoctor.System_ID = sDoctorModel.systemID;
            sNewDoctor.LicenseNo = sDoctorModel.licenseNo;
            sNewDoctor.Designation = sDoctorModel.designation;
            sNewDoctor.Specialty = sDoctorModel.specialty;
            sNewDoctor.IsDeleted = 0;
            sNewDoctor.CreatedDateTimestamp = sNow.ToUniversalTime();
            sNewDoctor.CreatedDate = sNow;
            sNewDoctor.CreatedBy = sDoctorModel.updatedBy;
            sNewDoctor.BranchID = sDoctorModel.branchID;

            if (DoctorRepository.AddDoctor(ConfigSettings.GetConfigurationSettings(), sNewDoctor, sDoctorModel.servicesLst))
            {
                sResp.StatusCode = (int)StatusCodes.Status200OK;
            }
            else
            {
                sResp.StatusCode = (int)StatusCodes.Status400BadRequest;
            }

            return Json(sResp);
        }

        /// <summary>
        /// Update Doctor
        /// </summary>
        /// <param name="sDoctorModel"></param>
        /// <returns></returns>
        public IActionResult UpdateDoctor(NewDoctorControllerModel sDoctorModel)
        {
            VPMSWeb.Models.ResponseStatusObject sResp = new VPMSWeb.Models.ResponseStatusObject();

            DoctorModel sUpdateDoctor = new DoctorModel();
            sUpdateDoctor.ID = Convert.ToInt32(sDoctorModel.ID);
            sUpdateDoctor.Name = sDoctorModel.doctorName;
            sUpdateDoctor.Gender = sDoctorModel.doctorGender;
            sUpdateDoctor.System_ID = sDoctorModel.systemID;
            sUpdateDoctor.LicenseNo = sDoctorModel.licenseNo;
            sUpdateDoctor.Designation = sDoctorModel.designation;
            sUpdateDoctor.Specialty = sDoctorModel.specialty;
            sUpdateDoctor.IsDeleted = 0;
            sUpdateDoctor.BranchID = sDoctorModel.branchID;
            sUpdateDoctor.UpdatedBy = sDoctorModel.updatedBy;

            if (DoctorRepository.UpdateDoctor(ConfigSettings.GetConfigurationSettings(), sUpdateDoctor, sDoctorModel.servicesLst))
            {
                sResp.StatusCode = (int)StatusCodes.Status200OK;
            }
            else
            {
                sResp.StatusCode = (int)StatusCodes.Status400BadRequest;
            }

            return Json(sResp);
        }

        /// <summary>
        /// Delete Doctor 
        /// </summary>
        /// <param name="iDoctorID"></param>
        /// <returns></returns>
        public IActionResult DeleteDoctor(int iDoctorID)
        {
            VPMSWeb.Models.ResponseStatusObject sResp = new VPMSWeb.Models.ResponseStatusObject();

            if (DoctorRepository.DeleteDoctor(ConfigSettings.GetConfigurationSettings(), iDoctorID))
            {
                sResp.StatusCode = (int)StatusCodes.Status200OK;
            }
            else
            {
                sResp.StatusCode = (int)StatusCodes.Status400BadRequest;
            }

            return Json(sResp);
        }

        /// <summary>
        /// Go to new Doctor Profile page
        /// </summary>
        /// <returns></returns>
        public IActionResult ViewDoctorProfile()
        {
            ViewData["DoctorProfile"] = null;

            int iTotal = 0;
            int roleIsAdmin = 0;
            int iOrganizationID = Convert.ToInt32(HttpContext.Session.GetString("OrganisationID"));
            int iBranchID = Convert.ToInt32(HttpContext.Session.GetString("BranchID"));
            roleIsAdmin = Convert.ToInt32(HttpContext.Session.GetString("IsAdmin"));

            int isSuperadmin = 0;
            var organizationObj = OrganizationRepository.GetOrganizationByID(iOrganizationID);
            if (organizationObj != null)
            {
                if (organizationObj.Level == 0 || organizationObj.Level == 1 || (organizationObj.Level == 2 && roleIsAdmin == 1))
                {
                    isSuperadmin = 1;
                }
                else
                {
                    isSuperadmin = 0;
                }
            }

            ObservableCollection<ServiceList> sServiceList = new ObservableCollection<ServiceList>();
            sServiceList = _servicesDBContext.GetServiceList(1, 1000, isSuperadmin, iBranchID, iOrganizationID, out iTotal);

            ViewData["ServicesList"] = sServiceList;

            return View("ViewDoctorProfile");
        }

        /// <summary>
        /// Edit / View Doctor Profile page 
        /// </summary>
        /// <param name="doctorid"></param>
        /// <param name="ViewType"></param>
        /// <returns></returns>
        [Route("/Doctor/ViewDoctorProfile/{doctorid}/{ViewType}")]
        public IActionResult ViewDoctorProfile(int? doctorid, String ViewType)
        {
            DoctorDetailModel sDoctorObject = new DoctorDetailModel();
            sDoctorObject = DoctorRepository.GetDoctorByID(ConfigSettings.GetConfigurationSettings(), doctorid.Value);

            List<DoctorServicesExtendedModel> sDoctorServiceList = new List<DoctorServicesExtendedModel>();
            sDoctorServiceList = DoctorRepository.GetDoctorServicesList(ConfigSettings.GetConfigurationSettings(), doctorid.Value);

            int iTotal = 0;
            int roleIsAdmin = 0;
            int iOrganizationID = Convert.ToInt32(HttpContext.Session.GetString("OrganisationID"));
            int iBranchID = Convert.ToInt32(HttpContext.Session.GetString("BranchID"));
            roleIsAdmin = Convert.ToInt32(HttpContext.Session.GetString("IsAdmin"));

            int isSuperadmin = 0;
            var organizationObj = OrganizationRepository.GetOrganizationByID(iOrganizationID);
            if (organizationObj != null)
            {
                if (organizationObj.Level == 0 || organizationObj.Level == 1 || (organizationObj.Level == 2 && roleIsAdmin == 1))
                {
                    isSuperadmin = 1;
                }
                else
                {
                    isSuperadmin = 0;
                }
            }

            ObservableCollection<ServiceList> sServiceList = new ObservableCollection<ServiceList>();
            sServiceList = _servicesDBContext.GetServiceList(1, 1000, isSuperadmin, iBranchID, iOrganizationID, out iTotal);

            ViewData["DoctorProfile"] = sDoctorObject;
            ViewData["ViewType"] = ViewType;
            ViewData["ServicesList"] = sServiceList;
            ViewData["DoctorServices"] = sDoctorServiceList;

            return View("ViewDoctorProfile", sDoctorObject);
        }

        /// <summary>
        /// Get Gender master List
        /// </summary>
        /// <returns></returns>
        public IActionResult GetGenderListDropdown()
        {
            var sMasterCodeObj = MastercodeRepository.GetMastercodeByGroup(ConfigSettings.GetConfigurationSettings(), sMasterDataGroupName);
            return Json(sMasterCodeObj);
        }
    }
}

VPMS/Views/Doctor/Index.cshtml
@inject VPMSWeb.Interface.IResourcesLocalizer LangResources
@inject IHttpContextAccessor httpContextaccessor

@{
    ViewData["Title"] = "Index";
    ViewData["SelectedMenu"] = "doctorMenu";

    var sessionBranchID = httpContextaccessor.HttpContext.Session.GetString("BranchID");
    var sessionOrganizationID = httpContextaccessor.HttpContext.Session.GetString("OrganisationID");
}

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-table.min.css" />
<link rel="stylesheet" href="~/css/Doctor.css" />
<script src="~/lib/bootstrap/dist/js/bootstrap-table.min.js"></script>

<script>
    var paginationLimit = 5;
    var pageSize = 10;
    var pageIndex = 1;
    var currentPage = 1;
    var totalPagination = 0;
    var startPagination = 1;
    var endPagination = 0;

    $(document).ready(function () {
        loadDoctorList('');

        $('#btnSearch').on('click', function (ctl) {
            currentPage = 1;

            loadDoctorList($('#txtSearch').val());
        });
    });

    function loadDoctorList(searchKeyword) 
    {
        $('#lbDocListingError').css('visibility', 'hidden');

        $.getJSON("/Doctor/GetDoctorViewList", {
            sKeyword: searchKeyword,
            branchID: @sessionBranchID,
            organizationID: '@sessionOrganizationID',
            pageSize: pageSize,
            pageIndex: currentPage
        }).done(function (result) {
            if (result.data != null & result.data.length > 0) {
                $('#tblDoctor').bootstrapTable('destroy');
                $('#tblDoctor').bootstrapTable({
                    data: result.data
                });

                /*--- Pagination ------*/
                populatePagingControl(result.totalRecord);
            }
            else
            {
                $('#tblDoctor').bootstrapTable('destroy');
                document.getElementById("pagination").hidden = true;
            }
        });
    }

    function mnDeleteOnClick(id) 
    {
        ShowConfirmCancelMsgBox("@Html.Raw(LangResources["Doctor_Title_DeleteDoctorRecord"])", 
                                "@Html.Raw(LangResources["Doctor_Message_ConfirmDeleteDoctor"])",
            function () {
                $.post("/Doctor/DeleteDoctor", {
                    iDoctorID: id
                }).done(function (result) {
                    if (result.StatusCode == 200){
                        window.location.reload();
                    }
                    else{
                        $('#lbDocListingError').html("@Html.Raw(LangResources["Doctor_Message_FailedToDeleteRecord"])");
                        $('#lbDocListingError').css('visibility', 'visible');
                    }
                });
            },
            function () { }
        );
    }

    function populateHideMenu(value, row){
        var hideMenuHtml = '<button type="button" class="btn" data-toggle="dropdown">' +
                           '<img class="doctorListingMoreIcon"  />' +
                           '</button>' +

                           '<div class="dropdown-menu containerBackground5" style="min-width: fit-content; font-size: 1vw;">' +
                           '<a class="dropdown-item" href="/Doctor/ViewDoctorProfile/' + value + '/View">' + '@Html.Raw(LangResources["Doctor_Menu_View"])' + '</a>' +
                           '<a class="dropdown-item" href="/Doctor/ViewDoctorProfile/' + value + '/Edit">' + '@Html.Raw(LangResources["Doctor_Menu_Edit"])' + '</a>' +
                           '<a class="dropdown-item" onclick="mnDeleteOnClick(' + value + ')">' + '@Html.Raw(LangResources["Doctor_Menu_Delete"])' + '</a>' +
                           '</div>';
        return hideMenuHtml;
    }

    function populatePagingControl(totalRecord) 
    {
        let total = totalRecord;
        if (total == 0) 
        { 
            document.getElementById("pagination").hidden = true; 
        }
        else 
        {
            document.getElementById("pagination").hidden = false;

            var totalPage = parseInt(total / pageSize);
            if (totalPage == 0) { 
                totalPage = totalPage + 1; 
            }

            if ((total > pageSize) && (total % pageSize) != 0) { 
                totalPage = totalPage + 1; 
            }

            totalPagination = totalPage;

            if (totalPage > paginationLimit) { 
                endPagination = paginationLimit 
            }
            else { 
                endPagination = totalPage; 
            }

            pagination(startPagination, endPagination);
        }

        if (currentPage == totalPagination) { 
            document.getElementById("nextButton").hidden = true; 
        }
        else { 
            document.getElementById("nextButton").hidden = false; 
        }
        if (currentPage == 1) { 
            document.getElementById("prevButton").hidden = true;
        }
        else { 
            document.getElementById("prevButton").hidden = false; 
        }
    }

    function pagination(start, end) 
    {
        var element = document.getElementById("paginationNumbering");

        element.innerHTML = "";
        for (let i = start; i < end + 1; i++) {
            var buttonClassName = "PaginationButton";

            if (currentPage == i) { 
                buttonClassName = "PaginationButtonSelected";
            }

            element.innerHTML = element.innerHTML +
                '<div>' +
                '<button onclick="changePage(this);" data-page="' + i + '" class="' + buttonClassName + '"> ' + ('0' + i).slice(-2) + ' </button>' +
                '</div>';
        }
    }

    function prev() {
        currentPage = currentPage - 1;
        loadDoctorList($('#txtSearch').val());
    }

    function next() {
        currentPage = currentPage + 1;

        loadDoctorList($('#txtSearch').val());
    }

    function changePage(page) {
        let pageNum = page.getAttribute("data-page");

        currentPage = Number(pageNum);
        loadDoctorList($('#txtSearch').val());
    }
</script>
<div class="row">
    <div class="row">
        <div class="col-md-12" style="height: auto;">
            <div class="row" style="height: auto;">
                <div class="col-md-12">
                    <label class="doctorPageTitle">@LangResources["Doctor_Title_Doctor"]</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3 ms-2">
        <!-- style="margin-left: 5px;"-->
        <div class="col-md-5 searchRowHeight">
            <div class="row searchRowHeight">
                <input id="txtSearch" type="text" class="form-control searchFields" placeholder="@LangResources["Doctor_Label_SearchByDoctorName"]" />
            </div>
        </div>
        <div class="col-md-1">
            <div class="row rowSearchMargin">
                <button id="btnSearch" type="button" class="btn btn-primary" style="margin: 5px; font-size: 12px;">
                    @LangResources["Doctor_Button_Search"]
                </button>
            </div>
        </div>
        <div class="col-md-4 searchRowHeight">&nbsp;</div>
        <div class="col-md-2 text-end searchRowHeight" >
            <div class="row searchRowHeight" >
                <div class="col-md-12">
                    <button id="btnCreate" type="button" class="btn btn-primary" style="margin: 5px; font-size: 12px;"
                            onclick="location.href='@Url.Action("ViewDoctorProfile", "Doctor")'">
                        <i class="bi bi-plus-circle"></i>
                        @LangResources["Doctor_Button_NewDoctor"]
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="row rowTableMargin" >
        <div class="col-md-12" style="height: 30px;">
            <label id="lbDocListingError"></label>
        </div>
        <div class="col-md-12">
            <table id="tblDoctor" class="table">
                <thead>
                    <tr>
                        <th scope="col" data-field="ID" class="text-center" style="width: 5%;">@LangResources["Doctor_Label_ColumnID"]</th>
                        <th scope="col" data-field="Name" class="text-center" style="width: 20%;">@LangResources["Doctor_Label_ColumnName"]</th>
                        <th scope="col" data-field="GenderName" class="text-center" style="width: 10%;">@LangResources["Doctor_Label_ColumnGender"]</th>
                        <th scope="col" data-field="LicenseNo" class="text-center" style="width: 10%;">@LangResources["Doctor_Label_ColumnLicenseNo"]</th>
                        <th scope="col" data-field="Designation" class="text-center" style="width: 25%;">@LangResources["Doctor_Label_ColumnDesignation"]</th>
                        <th scope="col" data-field="Specialty" class="text-center" style="width: 25%;">@LangResources["Doctor_Label_Specialty"]</th>
                        <th scope="col" data-field="ID" data-formatter="populateHideMenu" class="text-center" style="width: 5%;"></th>
                    </tr>
                </thead>
            </table>
            <div class="row">
                <div id="pagination" style="display: flex; justify-content: flex-end; margin-top: 15px;">
                    <div>
                        <button id="prevButton" class="textColor" onclick="prev();" style="width: 3vw; height: 3vw; margin-right: 2vw; text-align: center; display: flex; align-items: center; justify-content: center; background: transparent; border-style: none; font-weight: bold; font-size: 1vw;">@LangResources["Doctor_Button_Prev"]</button>
                    </div>
                    <div id="paginationNumbering" style="display: flex; justify-content: flex-end;">
                    </div>
                    <div>
                        <button id="nextButton" class="textColor" onclick="next();" style="width: 3vw; height: 3vw; margin-left: 1vw; text-align: center; display: flex; align-items: center; justify-content: center; background: transparent; border-style: none; font-weight: bold; font-size: 1vw;">@LangResources["Doctor_Button_Next"]</button>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>